/* Moja Pesmarica – Studio Kačar. Offline PWA; private signing key is NEVER part of the web app. */
'use strict';
const VERSION = '1.0';
const MAX_DEMO = 15;
const PUBLIC_KEY_B64 = 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEXdbtBfhFiFZPtZ+sjKRyT5zSaAEyttnCNxmXFD4kJtR8HFKIL9OUh3nHcLmHlPmz+KYSGdFj43cwTlko6KSSrQ==';
const DEFAULTS = () => ({songs: [], lists: [], settings: {theme:'light',font:'standard',scope:'all',performanceLight:false,fontSize:24,speed:3},license:'',installationId:''});
let state=DEFAULTS(), currentTab='internet', db=null, full=false, lastResults=[], activeListId=null;
let saving=Promise.resolve(), perf=null, frame=0, previousFrame=0, wakeLock=null, toastTimer=null;
const $=sel=>document.querySelector(sel), escapeHtml=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s||'').normalize('NFKC').trim().toLocaleLowerCase('sr');
const cmp=new Intl.Collator('sr',{sensitivity:'base',numeric:true});
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`;
const keyOf=s=>`${norm(s.title)}\u0000${norm(s.artist||'Nepoznat izvođač')}`;
const findSong=id=>state.songs.find(s=>s.id===id);
const findList=id=>state.lists.find(l=>l.id===id);
const optionSelect=(value,options)=>options.map(([v,txt])=>`<option value="${escapeHtml(v)}" ${v===value?'selected':''}>${escapeHtml(txt)}</option>`).join('');
const btn=(label,klass='ghost')=>`<button class="btn ${klass}">${label}</button>`;
function warn(text){const e=$('#toast');e.textContent=text;e.classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.add('hidden'),3500)}
function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open('MojaPesmaricaStudioKacarPWA',1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('app'))r.result.createObjectStore('app')};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function getStored(){return new Promise((resolve,reject)=>{const tx=db.transaction('app','readonly');const req=tx.objectStore('app').get('state');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
function save(){const snap=JSON.parse(JSON.stringify(state));saving=saving.catch(()=>{}).then(()=>new Promise((resolve,reject)=>{const tx=db.transaction('app','readwrite');tx.objectStore('app').put(snap,'state');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})).catch(e=>{console.error(e);warn('Čuvanje nije uspelo. Izvezi rezervnu kopiju i proveri prostor na telefonu.')});return saving}
function installId(){const b=new Uint8Array(10);crypto.getRandomValues(b);return [...b].map(x=>x.toString(16).padStart(2,'0')).join('').toUpperCase()}
function applyTheme(){document.documentElement.dataset.theme=state.settings.theme;document.documentElement.style.setProperty('--lyrics-font',({standard:'system-ui,-apple-system,sans-serif',serif:'Georgia,serif',mono:'ui-monospace,Menlo,monospace',condensed:'Arial Narrow,Arial,sans-serif'})[state.settings.font]||'system-ui')}
function header(){ $('#licenseTag').textContent=full?'FULL':`DEMO ${state.songs.length}/${MAX_DEMO}` }
function setTab(name){activeListId=null;closeModal();currentTab=name;render()}
function render(){header();applyTheme();document.querySelectorAll('[data-tab]').forEach(el=>{const active=el.dataset.tab===currentTab;el.classList.toggle('active',active);el.setAttribute('aria-current',active?'page':'false')});if(currentTab==='internet')renderInternet();else if(currentTab==='songs')renderSongs();else renderLists()}
function renderInternet(){
 $('#main').innerHTML=`<div class="heading"><h1>Pronađi tekst pesme</h1></div><p class="intro">Pronađi pesmu preko LRCLIB-a, pregledaj tekst i sačuvaj ga za nastupe bez interneta.</p>
 <section class="panel"><label class="label" for="searchTerm">Ime izvođača ili naziv pesme</label><input class="field" id="searchTerm" placeholder="Ime izvođača" autocomplete="off" enterkeyhint="search"><div class="buttons" style="margin-top:11px"><button class="btn grow" id="searchGo">Pretraži internet</button></div></section>
 <div class="heading"><h2 style="font-size:18px;margin:0">Rezultati</h2><span class="pill">LRCLIB</span></div>
 <div id="results"><p class="hint">Upiši naziv pesme ili izvođača. Rezultati će se prikazati ovde.</p></div>
 <section class="panel"><h2>Dodatna pretraga</h2><p class="hint">Pesmarica.rs i Google otvaraju se kao zasebne stranice. Ručno kopiran tekst možeš sačuvati kroz „Moje pesme → Dodaj“.</p><div class="buttons"><button class="btn green" id="pesmaricaGo">Pesmarica.rs ↗</button><button class="btn ghost" id="googleGo">Google ↗</button><button class="btn ghost" id="copyTerm">Kopiraj pojam</button></div></section>`;
 $('#searchGo').onclick=search;$('#searchTerm').onkeydown=e=>{if(e.key==='Enter')search()};
 $('#pesmaricaGo').onclick=()=>window.open('https://www.pesmarica.rs/pesme','_blank','noopener,noreferrer');
 $('#googleGo').onclick=()=>{const q=$('#searchTerm').value.trim();if(!q){warn('Unesi pojam za pretragu.');return}window.open('https://www.google.com/search?q='+encodeURIComponent(q+' tekst pesme'),'_blank','noopener,noreferrer')};
 $('#copyTerm').onclick=async()=>{try{await navigator.clipboard.writeText($('#searchTerm').value);warn('Pojam je kopiran.')}catch{warn('Označi i kopiraj pojam ručno.')}};
}
async function search(){const q=$('#searchTerm').value.trim();if(!q){warn('Unesi izvođača ili naziv pesme.');return}const dest=$('#results');dest.innerHTML='<div class="notice">Pretraga je u toku…</div>';$('#searchGo').disabled=true;
 try{const controller=new AbortController();const stop=setTimeout(()=>controller.abort(),17000);let response;try{response=await fetch('https://lrclib.net/api/search?q='+encodeURIComponent(q),{headers:{Accept:'application/json'},signal:controller.signal})}finally{clearTimeout(stop)}
 if(!response.ok)throw Error('Servis je vratio grešku '+response.status);const items=await response.json();if(!Array.isArray(items))throw Error('Neočekivan odgovor servisa');lastResults=items.slice(0,40);if(!lastResults.length){dest.innerHTML='<div class="notice">Nisu pronađene pesme. Pokušaj sa drugim nazivom ili Pesmarica.rs.</div>';return}
 dest.innerHTML=lastResults.map((s,i)=>`<article class="search-card"><h3>${escapeHtml(s.trackName||'Bez naslova')}</h3><p>${escapeHtml(s.artistName||'Nepoznat izvođač')}</p><div class="buttons"><button class="btn sm" data-result="${i}">Prikaži tekst</button><span class="pill">LRCLIB</span></div></article>`).join('');dest.querySelectorAll('[data-result]').forEach(b=>b.onclick=()=>showResult(lastResults[+b.dataset.result]));
 }catch(e){dest.innerHTML='<div class="notice">Pretraga nije dostupna. Proveri internet vezu ili probaj kasnije. '+escapeHtml(e.message)+'</div>'}finally{$('#searchGo').disabled=false}}
function plainLyrics(r){let txt=(r.plainLyrics||'').trim();if(!txt&&r.syncedLyrics)txt=r.syncedLyrics.replace(/^\[(?:ti|ar|al|by|offset):[^\]]*\]\s*$/gm,'').replace(/\[\d{1,3}:\d{2}(?:[.:]\d{1,3})?\]/g,'').trim();return txt}
function showResult(r){const lyrics=plainLyrics(r);const draft={title:r.trackName||'',artist:r.artistName||'',category:'Ostalo',lyrics,sourceUrl:'https://lrclib.net/',favorite:false};if(!lyrics){warn('Ovaj rezultat nema dostupan tekst. Možeš dodati pesmu ručno.');return}showEditor(draft)}
function renderSongs(){const sc=state.settings.scope;const filter=state.songs.filter(s=>sc==='all'||s.region===sc);const q=($('#libraryFilter')?.value||'').trim();const sorted=[...filter].sort((a,b)=>cmp.compare(a.artist,b.artist)||cmp.compare(a.title,b.title));
 $('#main').innerHTML=`<div class="heading"><h1>Moje pesme</h1><div class="buttons"><button class="btn ghost sm" id="songTools">⚙ Alati</button><button class="btn green sm" id="addSong">+ Dodaj</button></div></div><p class="intro">${full?'FULL – neograničeno pesama':`DEMO: ${state.songs.length} od ${MAX_DEMO} pesama`} · dostupno i bez interneta</p>
 <input id="libraryFilter" class="field" placeholder="Pretraži sačuvane pesme…"><div class="buttons" style="margin:11px 0 16px"><label class="small muted" for="sortSongs">Sortiraj:</label><select id="sortSongs" class="field" style="max-width:180px"><option value="artist">Izvođač A–Z</option><option value="title">Naziv A–Z</option></select><span class="counter" id="visibleCount"></span></div><div id="songsContainer"></div>`;
 $('#addSong').onclick=()=>showEditor({title:'',artist:'',category:'Ostalo',lyrics:'',region:'',sourceUrl:'',favorite:false});
 $('#songTools').onclick=showTools;
 const list=$('#songsContainer'),filterInput=$('#libraryFilter'),sort=$('#sortSongs'),count=$('#visibleCount');function show(){const text=norm(filterInput.value);const matches=sorted.filter(s=>norm(s.title+' '+s.artist).includes(text)).sort((a,b)=>sort.value==='title'?cmp.compare(a.title,b.title):cmp.compare(a.artist,b.artist)||cmp.compare(a.title,b.title));count.textContent=matches.length+' pesama';list.innerHTML=matches.length?matches.map(s=>`<article class="song-card"><div class="row space-between"><div><h3>${escapeHtml(s.title)}</h3><p>${escapeHtml(s.artist)}</p></div>${s.favorite?'<span class="pill">★</span>':''}</div><div class="buttons"><button class="btn sm" data-song="${escapeHtml(s.id)}">Otvori</button><button class="btn ghost sm" data-perf="${escapeHtml(s.id)}">⛶ Nastup</button></div></article>`).join(''):'<div class="notice">Nema pesama za ovaj prikaz. Dodaj pesmu ili promeni filter u podešavanjima.</div>';list.querySelectorAll('[data-song]').forEach(b=>b.onclick=()=>showDetail(b.dataset.song));list.querySelectorAll('[data-perf]').forEach(b=>b.onclick=()=>startPerformance(b.dataset.perf,null))}filterInput.oninput=show;sort.onchange=show;show();}
function closeModal(){const o=$('#overlay');o.classList.add('hidden');o.innerHTML=''}
function modal(title,markup){const o=$('#overlay');o.classList.remove('hidden');o.innerHTML=`<div class="modal"><div class="modal-head"><h2>${escapeHtml(title)}</h2><button class="btn ghost sm" id="modalClose" aria-label="Zatvori">✕</button></div>${markup}</div>`;$('#modalClose').onclick=closeModal;return o}
/** Izdvojeni alati: postojeći postupci uvoza ostaju neizmenjeni. */
function showTools(){
 modal('Uvoz i alati',`<p class="hint">Upravljanje tekstovima pesama. Za brisanje više pesama odjednom izaberi poslednju opciju.</p>
 <div class="stack tools-stack">
   <button class="btn ghost tool-action" id="toolsTxt"><span>⇧ &nbsp; Uvezi TXT pesmu</span><small>Dodaj pesmu iz tekstualne datoteke</small></button>
   <button class="btn ghost tool-action" id="toolsPdf"><span>⇧ &nbsp; Uvezi PDF tekst</span><small>PDF sa tekstualnim slojem; jedna pesma kao nacrt</small></button>
   <button class="btn danger tool-action" id="toolsDeleteMany"><span>▣ &nbsp; Obriši više pesama</span><small>Izaberi pesme i potvrdi zajedničko brisanje</small></button>
 </div><p class="hint" style="margin-top:14px">Napomena: skeniranje kamerom i automatsko izdvajanje više pesama iz PDF-a još nisu podržani u iPhone PWA verziji.</p>`);
 $('#toolsTxt').onclick=()=>{closeModal();pickFile('txt')};
 $('#toolsPdf').onclick=()=>{closeModal();pickFile('pdf')};
 $('#toolsDeleteMany').onclick=showBatchDelete;
}
function showBatchDelete(){
 if(!state.songs.length){modal('Obriši više pesama','<div class="notice">Nema sačuvanih pesama za brisanje.</div>');return}
 const selected=new Set();
 const collated=()=>[...state.songs].sort((a,b)=>cmp.compare(a.artist,b.artist)||cmp.compare(a.title,b.title));
 modal('Obriši više pesama',`<p class="hint">Označi pesme koje želiš da ukloniš. Možeš da pretražuješ spisak bez gubitka izbora.</p>
 <label for="deleteSearch" class="label">Pretraži pesme</label><input type="search" id="deleteSearch" class="field" placeholder="Naziv pesme ili izvođač" autocomplete="off">
 <div class="buttons bulk-toolbar"><button class="btn ghost sm" id="selectFiltered" type="button">Označi sve prikazane</button><button class="btn ghost sm" id="clearSelected" type="button">Poništi izbor</button></div>
 <div class="row space-between bulk-status"><b id="bulkCount" aria-live="polite">Označeno: 0</b><span class="small muted" id="bulkMatches"></span></div>
 <div id="bulkList" class="bulk-list" aria-label="Pesme za brisanje"></div>
 <div class="buttons bulk-footer"><button class="btn danger grow" id="deleteSelected" disabled>Obriši izabrane (0)</button><button class="btn ghost" id="cancelBulk">Otkaži</button></div>
 <p class="hint">Brisanje je trajno i uklanja izabrane pesme iz svih korisničkih lista. Nazivi i ostale pesme u listama ostaju sačuvani. Pre brisanja napravi rezervnu kopiju.</p>`);
 const input=$('#deleteSearch'),list=$('#bulkList'),count=$('#bulkCount'),matches=$('#bulkMatches'),del=$('#deleteSelected');
 const visible=()=>{const q=norm(input.value);return collated().filter(s=>norm(s.title+' '+s.artist).includes(q))};
 function update(){const songs=visible();count.textContent=`Označeno: ${selected.size}`;matches.textContent=`Prikazano: ${songs.length}`;del.textContent=`Obriši izabrane (${selected.size})`;del.disabled=selected.size===0;
  list.innerHTML=songs.length?songs.map(s=>`<label class="bulk-song"><input type="checkbox" data-bulk-id="${escapeHtml(s.id)}" ${selected.has(s.id)?'checked':''}><span><strong>${escapeHtml(s.title)}</strong><small>${escapeHtml(s.artist)}</small></span></label>`).join(''):'<div class="notice">Nema pesama za ovu pretragu.</div>';
  list.querySelectorAll('[data-bulk-id]').forEach(check=>check.onchange=()=>{const id=check.dataset.bulkId;if(check.checked)selected.add(id);else selected.delete(id);count.textContent=`Označeno: ${selected.size}`;del.textContent=`Obriši izabrane (${selected.size})`;del.disabled=selected.size===0});
 }
 input.oninput=update;
 $('#selectFiltered').onclick=()=>{for(const song of visible())selected.add(song.id);update()};
 $('#clearSelected').onclick=()=>{selected.clear();update()};
 $('#cancelBulk').onclick=closeModal;
 del.onclick=async()=>{const present=new Set(state.songs.map(s=>s.id));const ids=new Set([...selected].filter(id=>present.has(id)));if(!ids.size){warn('Prvo označi pesme.');update();return}
  if(!confirm(`Trajno obrisati ${ids.size} ${ids.size===1?'pesmu':'označenih pesama'}?\n\nOva radnja se ne može poništiti.`))return;
  state.songs=state.songs.filter(s=>!ids.has(s.id));for(const group of state.lists)group.songIDs=group.songIDs.filter(id=>!ids.has(id));
  await save();closeModal();currentTab='songs';render();warn(`Obrisano je ${ids.size} pesama.`);
 };
 update();input.focus();
}
function showEditor(initial){const draft={...initial};const editing=!!draft.id;
 modal(editing?'Uredi pesmu':'Dodaj pesmu',`<label class="label" for="songTitle">Naslov pesme</label><input class="field" id="songTitle" maxlength="220" value="${escapeHtml(draft.title)}">
 <label class="label" for="songArtist">Ime izvođača</label><input class="field" id="songArtist" maxlength="220" value="${escapeHtml(draft.artist)}">
 <label class="label" for="songCat">Žanr</label><input class="field" id="songCat" maxlength="120" value="${escapeHtml(draft.category||'Ostalo')}">
 <label class="label" for="songRegion">Izvođač</label><select class="field" id="songRegion">${optionSelect(draft.region||'',[['','Nepoznato'],['domaci','Domaći izvođač'],['strani','Strani izvođač']])}</select>
 <label class="label" for="songLyrics">Tekst pesme</label><textarea class="field" id="songLyrics" spellcheck="false"></textarea><p class="hint">U DEMO režimu možeš uređivati svih 15 postojećih pesama, ali ne možeš dodati šesnaestu.</p>
 <div class="buttons"><button class="btn green grow" id="saveSong">Sačuvaj pesmu</button><button class="btn ghost" id="cancelSong">Otkaži</button></div>`);
 $('#songLyrics').value=draft.lyrics||'';$('#cancelSong').onclick=closeModal;
 $('#saveSong').onclick=async()=>{const song={...draft,id:draft.id||uid(),title:$('#songTitle').value.trim(),artist:$('#songArtist').value.trim()||'Nepoznat izvođač',category:$('#songCat').value.trim()||'Ostalo',region:$('#songRegion').value,lyrics:$('#songLyrics').value.trim(),sourceUrl:draft.sourceUrl||'',favorite:!!draft.favorite,updatedAt:new Date().toISOString()};
 if(!song.title||!song.lyrics){warn('Naslov i tekst pesme su obavezni.');return}if(state.songs.some(s=>s.id!==song.id&&keyOf(s)===keyOf(song))){warn('Pesma sa tim naslovom i izvođačem već postoji.');return}if(!editing&&!full&&state.songs.length>=MAX_DEMO){warn('DEMO je popunjen (15 pesama). Otvori ⋮ → Aktiviraj FULL.');return}const index=state.songs.findIndex(s=>s.id===song.id);if(index<0)state.songs.push(song);else state.songs[index]=song;await save();closeModal();currentTab='songs';render();warn(editing?'Pesma je izmenjena.':'Pesma je sačuvana.')};}
function showDetail(id){const s=findSong(id);if(!s)return;const o=modal(s.title,`<p class="muted">${escapeHtml(s.artist)}</p><pre class="detail-text" id="detailLyrics"></pre><div class="buttons"><button class="btn green sm" id="detailPerform">⛶ Režim nastupa</button><button class="btn ghost sm" id="detailEdit">Uredi</button><button class="btn ghost sm" id="detailShare">Podeli</button><button class="btn ghost sm" id="detailFavorite">${s.favorite?'★ Ukloni iz omiljenih':'☆ Omiljena'}</button><button class="btn ghost sm" id="detailList">Dodaj u listu</button><button class="btn danger sm" id="detailDelete">Obriši</button></div>`);
 $('#detailLyrics').textContent=s.lyrics;
 $('#detailPerform').onclick=()=>startPerformance(id,activeListId);$('#detailEdit').onclick=()=>showEditor(s);
 $('#detailShare').onclick=async()=>{const text=s.title+' – '+s.artist+'\n\n'+s.lyrics;try{if(navigator.share)await navigator.share({title:s.title,text});else await navigator.clipboard.writeText(text)}catch(e){if(e.name!=='AbortError')warn('Deljenje nije uspelo.')} };
 $('#detailFavorite').onclick=async()=>{s.favorite=!s.favorite;await save();showDetail(id)};
 $('#detailList').onclick=()=>chooseListForSong(id);
 $('#detailDelete').onclick=async()=>{if(!confirm('Trajno obrisati pesmu „'+s.title+'“?'))return;state.songs=state.songs.filter(x=>x.id!==id);state.lists.forEach(l=>l.songIDs=l.songIDs.filter(x=>x!==id));await save();closeModal();render();warn('Pesma je obrisana.')};
}
function chooseListForSong(id){const lists=state.lists;modal('Dodaj u korisničku listu',lists.length?`<div class="stack">${lists.map(l=>`<button class="btn ghost" data-assign="${escapeHtml(l.id)}">${escapeHtml(l.name)} ${l.songIDs.includes(id)?'✓':''}</button>`).join('')}</div>`:'<p class="hint">Nema lista. Otvori „Moje liste“ i napravi prvu listu.</p>');document.querySelectorAll('[data-assign]').forEach(b=>b.onclick=async()=>{const l=findList(b.dataset.assign);if(l&&!l.songIDs.includes(id))l.songIDs.push(id);await save();closeModal();warn('Pesma je dodata u listu.')})}
function renderLists(){ $('#main').innerHTML=`<div class="heading"><h1>Moje liste</h1><button class="btn green sm" id="newList">+ Nova lista</button></div><p class="intro">Repertoari za nastup. Ista pesma može biti u više lista; brisanje iz liste ne briše pesmu.</p><div id="listsBox">${state.lists.length?state.lists.map(l=>`<article class="list-card"><h3>${escapeHtml(l.name)}</h3><p>${l.songIDs.length} pesama</p><div class="buttons"><button class="btn sm" data-open-list="${escapeHtml(l.id)}">Otvori listu</button><button class="btn ghost sm" data-rename-list="${escapeHtml(l.id)}">Preimenuj</button><button class="btn danger sm" data-delete-list="${escapeHtml(l.id)}">Obriši</button></div></article>`).join(''):'<div class="notice">Još nema korisničkih lista. Napravi „Početak večeri“, „Brze“ ili svoju listu.</div>'}</div>`;
 $('#newList').onclick=()=>askList();document.querySelectorAll('[data-open-list]').forEach(b=>b.onclick=()=>showList(b.dataset.openList));document.querySelectorAll('[data-rename-list]').forEach(b=>b.onclick=()=>askList(b.dataset.renameList));document.querySelectorAll('[data-delete-list]').forEach(b=>b.onclick=async()=>{if(!confirm('Obrisati listu? Pesme ostaju sačuvane.'))return;state.lists=state.lists.filter(l=>l.id!==b.dataset.deleteList);await save();render()})}
function askList(id=null){const l=id?findList(id):null;const name=prompt(l?'Novi naziv liste:':'Naziv nove liste:',l?.name||'');if(name===null)return;const trimmed=name.trim();if(!trimmed){warn('Unesi naziv liste.');return}if(state.lists.some(x=>x.id!==id&&norm(x.name)===norm(trimmed))){warn('Lista sa tim nazivom već postoji.');return}if(l)l.name=trimmed;else state.lists.push({id:uid(),name:trimmed,songIDs:[]});save();render()}
function showList(id){const l=findList(id);if(!l){renderLists();return}activeListId=id;const songs=l.songIDs.map(findSong).filter(Boolean);
 $('#main').innerHTML=`<div class="heading"><button class="btn ghost sm" id="backLists">← Liste</button><h1 style="font-size:21px">${escapeHtml(l.name)}</h1></div><div class="buttons" style="margin-bottom:15px"><button class="btn green sm" id="addListSongs">+ Dodaj pesme</button>${songs.length?'<button class="btn sm" id="runList">⛶ Pokreni nastup</button>':''}</div><div id="listSongRows">${songs.length?songs.map((s,i)=>`<article class="list-song"><b>${i+1}. ${escapeHtml(s.title)}</b><small>${escapeHtml(s.artist)}</small><div class="buttons" style="margin-top:10px"><button class="btn sm" data-view-song="${escapeHtml(s.id)}">Otvori</button><button class="btn ghost sm" data-up="${i}" ${i===0?'disabled':''}>↑</button><button class="btn ghost sm" data-down="${i}" ${i===songs.length-1?'disabled':''}>↓</button><button class="btn danger sm" data-remove="${escapeHtml(s.id)}">Ukloni</button></div></article>`).join(''):'<div class="notice">Dodaj pesme iz svoje pesmarice.</div>'}</div>`;
 $('#backLists').onclick=()=>{activeListId=null;renderLists()};$('#addListSongs').onclick=()=>chooseSongsForList(id);if($('#runList'))$('#runList').onclick=()=>startPerformance(songs[0].id,id);
 document.querySelectorAll('[data-view-song]').forEach(b=>b.onclick=()=>showDetail(b.dataset.viewSong));document.querySelectorAll('[data-up]').forEach(b=>b.onclick=async()=>{const i=+b.dataset.up;[l.songIDs[i-1],l.songIDs[i]]=[l.songIDs[i],l.songIDs[i-1]];await save();showList(id)});document.querySelectorAll('[data-down]').forEach(b=>b.onclick=async()=>{const i=+b.dataset.down;[l.songIDs[i+1],l.songIDs[i]]=[l.songIDs[i],l.songIDs[i+1]];await save();showList(id)});document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=async()=>{l.songIDs=l.songIDs.filter(sid=>sid!==b.dataset.remove);await save();showList(id)})}
function chooseSongsForList(id){const l=findList(id);modal('Dodaj pesme u listu',`<p class="hint">Izaberi pesmu. Postojeće pesme se ne dupliraju.</p><div class="stack">${state.songs.filter(s=>!l.songIDs.includes(s.id)).sort((a,b)=>cmp.compare(a.title,b.title)).map(s=>`<button class="btn ghost" data-add-song="${escapeHtml(s.id)}">${escapeHtml(s.title)} – ${escapeHtml(s.artist)}</button>`).join('')||'<p class="hint">Sve pesme su već u listi.</p>'}</div>`);document.querySelectorAll('[data-add-song]').forEach(b=>b.onclick=async()=>{l.songIDs.push(b.dataset.addSong);await save();closeModal();showList(id);warn('Pesma je dodata.')})}
function showSettings(){modal('Podešavanja',`<label class="label" for="settingTheme">Izgled aplikacije</label><select class="field" id="settingTheme">${optionSelect(state.settings.theme,[['light','Bela tema'],['dark','Crna tema']])}</select><label class="label" for="settingFont">Font pesama</label><select class="field" id="settingFont">${optionSelect(state.settings.font,[['standard','Standardni'],['serif','Serif'],['mono','Monospace'],['condensed','Uži font']])}</select><label class="label" for="settingScope">Prikaz izvođača u mojim pesmama</label><select class="field" id="settingScope">${optionSelect(state.settings.scope,[['all','Svi izvođači'],['domaci','Domaći izvođači'],['strani','Strani izvođači']])}</select><p class="hint">Izvođače sam označavaš kada uređuješ pesmu. Internet servis ne daje pouzdan podatak o poreklu izvođača.</p><button class="btn green" id="saveSettings">Sačuvaj podešavanja</button>`);$('#saveSettings').onclick=async()=>{state.settings.theme=$('#settingTheme').value;state.settings.font=$('#settingFont').value;state.settings.scope=$('#settingScope').value;await save();closeModal();render();warn('Podešavanja su sačuvana.')}}
function about(){modal('O aplikaciji',`<div class="center"><h2>♫ MOJA PESMARICA</h2><p><b>Verzija ${VERSION}</b></p></div><p>Moja Pesmarica je aplikacija namenjena muzičarima, pevačima i izvođačima koji žele da sve tekstove pesama i repertoare imaju na jednom mestu.</p><p>Aplikacija omogućava pretragu tekstova pesama, njihovo čuvanje za korišćenje bez interneta, uređivanje i organizovanje u sopstvene liste.</p><p>Uključuje režim nastupa preko celog ekrana, automatsko pomeranje teksta, podešavanje slova i rezervne kopije.</p><hr class="separator"><p class="center"><b>Razvio i proizveo: STUDIO KAČAR</b><br><small>© 2026 Studio Kačar. Sva prava zadržana.</small></p><p class="hint center">PWA verzija za iPhone • Ne zahteva Apple razvojni potpis • Podaci ostaju u memoriji Safari aplikacije</p>`)}
function backup(){const names=new Map(state.songs.map(s=>[s.id,{title:s.title,artist:s.artist}]));const payload={format:'moja-pesmarica',version:2,songs:state.songs.map(s=>({title:s.title,artist:s.artist,category:s.category||'Ostalo',lyrics:s.lyrics,sourceUrl:s.sourceUrl||'',favorite:!!s.favorite})),setlists:state.lists.map(l=>({name:l.name,songs:l.songIDs.map(id=>names.get(id)).filter(Boolean)}))};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='MojaPesmarica_StudioKacar_backup_'+new Date().toISOString().slice(0,10)+'.json';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);warn('Rezervna kopija je pripremljena za čuvanje u Files.')}
async function restore(text){let payload;try{payload=JSON.parse(text)}catch{throw Error('Datoteka nije ispravan JSON.')}if(payload?.format!=='moja-pesmarica'||!Array.isArray(payload.songs)||payload.songs.length>50000)throw Error('Datoteka nije rezervna kopija Moje Pesmarice.');const songs=state.songs.map(s=>({...s})), keys=new Set(songs.map(keyOf));let added=0,linked=0;
 for(const r of payload.songs){if(!r||typeof r.title!=='string'||typeof r.lyrics!=='string')continue;const title=r.title.trim(),lyrics=r.lyrics.trim(),artist=String(r.artist||'Nepoznat izvođač').trim();if(!title||!lyrics)continue;const draft={id:uid(),title,artist,lyrics,category:String(r.category||'Ostalo'),sourceUrl:String(r.sourceUrl||''),favorite:!!r.favorite,region:'',updatedAt:new Date().toISOString()};if(!keys.has(keyOf(draft))){keys.add(keyOf(draft));songs.push(draft);added++}}
 if(!full&&songs.length>MAX_DEMO)throw Error('Uvoz bi prekoračio DEMO ograničenje od 15 pesama. Aktiviraj FULL. Nijedna pesma nije promenjena.');const lists=state.lists.map(l=>({id:l.id,name:l.name,songIDs:[...l.songIDs]})),lookup=new Map(songs.map(s=>[keyOf(s),s.id]));for(const r of (payload.setlists||payload.lists||[])){if(!r||typeof r.name!=='string'||!r.name.trim())continue;const name=r.name.trim();let l=lists.find(v=>norm(v.name)===norm(name));if(!l){l={id:uid(),name,songIDs:[]};lists.push(l)}for(const sr of Array.isArray(r.songs)?r.songs:[]){const id=lookup.get(keyOf({title:sr.title,artist:sr.artist}));if(id&&!l.songIDs.includes(id)){l.songIDs.push(id);linked++}}}state.songs=songs;state.lists=lists;await save();render();warn(`Uvezeno ${added} pesama i ${linked} veza u listama.`)}
function pickFile(kind){const inp=$('#fileInput');inp.value='';inp.accept=kind==='restore'?'.json,application/json':kind==='txt'?'.txt,text/plain':'.pdf,application/pdf';inp.onchange=async()=>{const f=inp.files?.[0];if(!f)return;if(f.size>20_000_000){warn('Datoteka je prevelika (najviše 20 MB).');return}try{if(kind==='restore'){await restore(await f.text())}else if(kind==='txt'){const lyrics=await f.text();showEditor({title:f.name.replace(/\.txt$/i,''),artist:'',category:'Ostalo',lyrics,sourceUrl:''})}else{await parsePdf(f)}}catch(e){warn(e.message||'Greška pri uvozu.')}};inp.click()}
async function parsePdf(file){warn('Učitavanje PDF biblioteke zahteva internet…');if(!window.pdfjsLib){await new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js';script.onload=resolve;script.onerror=()=>reject(Error('PDF biblioteka nije dostupna. Probaj ponovo uz internet.'));document.head.append(script)});window.pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js'}const pdf=await window.pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise;if(pdf.numPages>150)throw Error('PDF ima previše stranica.');const lines=[];for(let p=1;p<=pdf.numPages;p++){const page=await pdf.getPage(p);const content=await page.getTextContent();let byY=new Map();for(const t of content.items){if(!t.str.trim())continue;const y=Math.round(t.transform[5]/4)*4;const arr=byY.get(y)||[];arr.push({x:t.transform[4],text:t.str});byY.set(y,arr)}for(const y of [...byY.keys()].sort((a,b)=>b-a))lines.push(byY.get(y).sort((a,b)=>a.x-b.x).map(t=>t.text).join(' ').trim());lines.push('')}const text=lines.join('\n').trim();if(!text)throw Error('PDF ne sadrži tekstualni sloj. Za skenirani PDF potreban je OCR.');showEditor({title:file.name.replace(/\.pdf$/i,''),artist:'',category:'Ostalo',lyrics:text,sourceUrl:''});warn('PDF je učitan kao nacrt. Proveri prelome i ručno razdvoji pesme.')}
// Java SE signs ECDSA with ASN.1 DER; WebCrypto P-256 expects 64-byte r||s.
function b64bytes(v){v=v.replace(/-/g,'+').replace(/_/g,'/');v+='='.repeat((4-v.length%4)%4);const str=atob(v);return Uint8Array.from(str,c=>c.charCodeAt(0))}
function derToP1363(sig){let i=0;const readLength=()=>{let n=sig[i++];if(n&0x80){const count=n&0x7f;if(!count||count>2)throw Error('length');n=0;for(let j=0;j<count;j++)n=(n<<8)|sig[i++]}return n};if(sig[i++]!==0x30)throw Error('sequence');const total=readLength(),end=i+total;if(end!==sig.length)throw Error('size');const readInt=()=>{if(sig[i++]!==0x02)throw Error('integer');const len=readLength();const v=sig.slice(i,i+len);i+=len;while(v.length>32&&v[0]!==0)throw Error('integer size');let arr=v;while(arr.length>32&&arr[0]===0)arr=arr.slice(1);if(arr.length>32)throw Error('integer size');const out=new Uint8Array(32);out.set(arr,32-arr.length);return out};const r=readInt(),s=readInt();if(i!==end)throw Error('trailing');const out=new Uint8Array(64);out.set(r);out.set(s,32);return out}
async function validLicense(code){if(typeof code!=='string'||code.length>1024)return false;const parts=code.trim().replace(/\s/g,'').split('.');if(parts.length!==3||parts[0]!=='SK1')return false;try{const payload=b64bytes(parts[1]),signature=derToP1363(b64bytes(parts[2]));if(new TextDecoder().decode(payload)!=='SK-FULL-1|'+state.installationId)return false;const key=await crypto.subtle.importKey('spki',b64bytes(PUBLIC_KEY_B64),{name:'ECDSA',namedCurve:'P-256'},false,['verify']);return await crypto.subtle.verify({name:'ECDSA',hash:'SHA-256'},key,signature,payload)}catch{return false}}
async function activate(){const formatted=state.installationId.match(/.{1,4}/g).join('-');modal('Aktiviraj FULL',`<p>DEMO dozvoljava ${MAX_DEMO} pesama. Za FULL kod pošalji Studio Kačar svoj ID instalacije:</p><div class="panel" style="font-family:monospace;overflow-wrap:anywhere;font-weight:700">${formatted}</div><button class="btn ghost sm" id="copyId">Kopiraj ID instalacije</button><label class="label" for="licenseInput">FULL aktivacioni kod</label><textarea class="field" id="licenseInput" rows="4" style="min-height:90px" placeholder="SK1.…"></textarea><div class="buttons"><button class="btn green" id="applyCode">Aktiviraj FULL</button></div><p class="hint">Koristi se isti sistem potpisanih licenci kao u Android aplikaciji. Kod je vezan za ID ove iPhone instalacije; postojeći kod izdat za Android ID nije prenosiv.</p>${full?'<p class="pill">FULL je već aktiviran ✓</p>':''}`);$('#copyId').onclick=async()=>{try{await navigator.clipboard.writeText(formatted);warn('ID je kopiran.')}catch{warn('Označi ID i kopiraj ga ručno.')}};$('#applyCode').onclick=async()=>{const code=$('#licenseInput').value.trim();if(!await validLicense(code)){warn('Nevažeći kod ili kod za drugi uređaj.');return}state.license=code;full=true;await save();closeModal();render();warn('FULL je aktiviran – nema ograničenja broja pesama!')}}
function openMenu(){const box=$('#menu');const now=box.classList.toggle('hidden');$('#menuBtn').setAttribute('aria-expanded',String(!now))}
function menuAction(action){$('#menu').classList.add('hidden');$('#menuBtn').setAttribute('aria-expanded','false');if(action==='settings')showSettings();else if(action==='tools')showTools();else if(action==='txt'||action==='pdf'||action==='restore')pickFile(action);else if(action==='backup')backup();else if(action==='activate')activate();else if(action==='about')about()}
function startPerformance(songID,listID=null){const ordered=(listID?findList(listID)?.songIDs:state.songs.slice().sort((a,b)=>cmp.compare(a.title,b.title)).map(s=>s.id))||[];let index=ordered.indexOf(songID);if(index<0){ordered.unshift(songID);index=0}closeModal();perf={ordered,index,light:!!state.settings.performanceLight,fontSize:state.settings.fontSize||24,speed:state.settings.speed||3,playing:false};document.body.style.overflow='hidden';drawPerf();if(navigator.wakeLock?.request)navigator.wakeLock.request('screen').then(lock=>wakeLock=lock).catch(()=>{});}
function stopPerformance(){if(!perf)return;perf=null;cancelAnimationFrame(frame);wakeLock?.release?.().catch(()=>{});wakeLock=null;$('#performance')?.remove();document.body.style.overflow='';render()}
function drawPerf(){let holder=$('#performance');if(!holder){holder=document.createElement('section');holder.id='performance';document.body.append(holder)}const song=findSong(perf.ordered[perf.index]);if(!song){stopPerformance();return}holder.className='full-performance'+(perf.light?' light':'');holder.style.setProperty('--perf-font-size',perf.fontSize+'px');holder.innerHTML=`<div class="performance-head"><button class="perf-icon" id="closePerf">✕</button><div><h2>${escapeHtml(song.title)}</h2><small>${escapeHtml(song.artist)}</small></div><button class="perf-icon" id="togglePerfTheme">◐</button></div><div class="performance-body" id="perfLyrics" aria-label="Tekst pesme"></div><div class="performance-controls" id="perfControls"><div class="buttons"><button class="btn" id="prevPerf" ${perf.index===0?'disabled':''}>⟵</button><button class="btn" id="smallerPerf">A−</button><button class="btn ${perf.playing?'green':''}" id="playPerf">${perf.playing?'⏸ Pauza':'▶ Pokreni'}</button><button class="btn" id="largerPerf">A+</button><button class="btn" id="nextPerf" ${perf.index===perf.ordered.length-1?'disabled':''}>⟶</button></div><div class="row"><span class="small">Brzina</span><input class="range" id="perfSpeed" type="range" min="1" max="8" step="1" value="${perf.speed}" aria-label="Brzina pomeranja"><b id="speedValue">${perf.speed}/8</b></div><div class="buttons"><button class="btn" id="hidePerf">Sakrij kontrole</button><span class="small" style="opacity:.66">Pomeranje prstom pauzira skrolovanje</span></div></div><button id="showPerf" class="perf-icon hidden" style="position:absolute;right:15px;bottom:calc(16px + env(safe-area-inset-bottom))">Pokaži kontrole</button>`;
 $('#perfLyrics').textContent=song.lyrics;$('#closePerf').onclick=stopPerformance;
 $('#togglePerfTheme').onclick=async()=>{perf.light=!perf.light;state.settings.performanceLight=perf.light;await save();holder.classList.toggle('light',perf.light)};
 $('#playPerf').onclick=()=>{perf.playing=!perf.playing;$('#playPerf').textContent=perf.playing?'⏸ Pauza':'▶ Pokreni';$('#playPerf').classList.toggle('green',perf.playing);previousFrame=0;cancelAnimationFrame(frame);if(perf.playing)frame=requestAnimationFrame(scrollFrame)};
 $('#prevPerf').onclick=()=>changePerformance(-1);$('#nextPerf').onclick=()=>changePerformance(1);
 $('#smallerPerf').onclick=()=>sizePerformance(-2);$('#largerPerf').onclick=()=>sizePerformance(2);
 $('#perfSpeed').oninput=e=>{perf.speed=+e.target.value;$('#speedValue').textContent=perf.speed+'/8';state.settings.speed=perf.speed;save()};
 $('#perfLyrics').addEventListener('touchstart',pauseScroll,{passive:true});$('#perfLyrics').addEventListener('wheel',pauseScroll,{passive:true});
 $('#hidePerf').onclick=()=>{$('#perfControls').classList.add('hidden');$('#showPerf').classList.remove('hidden')};$('#showPerf').onclick=()=>{$('#perfControls').classList.remove('hidden');$('#showPerf').classList.add('hidden')};if(perf.playing){previousFrame=0;frame=requestAnimationFrame(scrollFrame)}
}
function sizePerformance(change){perf.fontSize=Math.max(14,Math.min(54,perf.fontSize+change));$('#performance').style.setProperty('--perf-font-size',perf.fontSize+'px');state.settings.fontSize=perf.fontSize;save()}
function pauseScroll(){if(!perf?.playing)return;perf.playing=false;cancelAnimationFrame(frame);const b=$('#playPerf');if(b){b.textContent='▶ Pokreni';b.classList.remove('green')}}
function scrollFrame(timestamp){if(!perf?.playing)return;const el=$('#perfLyrics');if(!el)return;if(!previousFrame)previousFrame=timestamp;const elapsed=Math.min((timestamp-previousFrame)/1000,.08);previousFrame=timestamp;el.scrollTop+=(6+perf.speed*8)*elapsed;if(el.scrollTop>=el.scrollHeight-el.clientHeight-1){pauseScroll();return}frame=requestAnimationFrame(scrollFrame)}
function changePerformance(direction){perf.index=Math.max(0,Math.min(perf.ordered.length-1,perf.index+direction));perf.playing=false;cancelAnimationFrame(frame);drawPerf()}
async function start(){if(!('indexedDB'in window)){document.body.innerHTML='<p style="padding:24px">Ova aplikacija zahteva Safari sa uključenim lokalnim čuvanjem podataka.</p>';return}try{db=await openDb();const stored=await getStored();if(stored&&Array.isArray(stored.songs)&&Array.isArray(stored.lists))state={...DEFAULTS(),...stored,settings:{...DEFAULTS().settings,...stored.settings}};if(!/^[0-9A-F]{20}$/.test(state.installationId))state.installationId=installId();full=await validLicense(state.license);await save();$('#menuBtn').onclick=openMenu;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));$('#menu').querySelectorAll('[data-menu]').forEach(b=>b.onclick=()=>menuAction(b.dataset.menu));document.addEventListener('click',e=>{if(!e.target.closest('#menu, #menuBtn')){$('#menu').classList.add('hidden');$('#menuBtn').setAttribute('aria-expanded','false')}});currentTab='internet';render();if('serviceWorker' in navigator && (location.protocol === 'https:' || location.hostname === 'localhost')){navigator.serviceWorker?.register('./sw.js').catch(console.warn)}}catch(e){console.error(e);document.querySelector('#main').innerHTML='<div class="notice">Pokretanje nije uspelo: '+escapeHtml(e.message)+'. Proveri da Safari dozvoljava lokalno čuvanje podataka.</div>'}}
window.addEventListener('DOMContentLoaded',start);
